### ISSUE TITLE
[BUG] NAM 0.7.2 - Training with 2_0_0.wav failed to recognize blips.

### ISSUE THREAD

**Issue by raidolo** [sdatkinson/neural-amp-modeler#299] opened 2023-07-31 23:24 UTC
**Describe the bug**
Training with 2_0_0.wav failed to recognize blips. 
My chain is output of the interface direct to pedal, then back into ther interface, not so noisy from what I'm earing in the DAW.

**To Reproduce**
1. intalled the conda gpu env
2. recorded the reamp and exported using time based selection
3. trained with NAM 0.7.2 
4. Here is the first graph:
![image](https://github.com/sdatkinson/neural-amp-modeler/assets/25846804/7dfcfffa-9218-42ac-91e8-5dd36853f4e2)

5. then the second one:

![image](https://github.com/sdatkinson/neural-amp-modeler/assets/25846804/6bd8294c-e8d7-4256-a594-8cc1b4a63149)

6. And that's the Error: 
![image](https://github.com/sdatkinson/neural-amp-modeler/assets/25846804/d8dc453e-c29e-4a04-a2db-1cba5b7a8835)

**Expected behavior**
Train the model correctly :)

**OutputFile**

Here is the Output file 
[output_riot_drive75_level50_tone50_render.zip](https://github.com/sdatkinson/neural-amp-modeler/files/12222902/output_riot_drive75_level50_tone50_render.zip)

**Desktop (please complete the following information):**
 - OS Windows 10 21H2
 - Local Cuda Training with RTX 2060
 - 0.7.2 commit 06547c8

**Additional context**
I can successfully train with 1_1_1.wav

**Comment by sdatkinson** [comment] 2023-08-01 01:12
Thanks for the Issue. The details are very helpful.

The issue isn't that the blips aren't recognized. It's that the pedal reacts so differently to them that you might not be able to get a low ESR--the input was the same, but the two ways it reacted are "very" different from each other (ESR between 0.03 and 0.05--see the numbers in your screencap).

This didn't happen with v1_1_1.wav because it doesn't have any repeats in the signal to be able to catch that your reamp is doing this (It just didn't check at all).

If you could do me a favor: try ignoring this warning by checking the box in the GUI trainer in the corner, and let me know how it turns out. I need more data to understand what a better threshold would be for triggering that warning.

**Comment by raidolo** [comment] 2023-08-01 01:22
Hi Steve,

I already did that and the training was successful, I ended up with ESR 0.0104 something...with 100 epochs. Even like this I've played the NAM and the result was good, I was not able to tele the difference from the real pedal in a brief test, even with only 100 EP. I've deleted the file, cause it was just a test, but I could train it again if you wish...

**Comment by sdatkinson** [comment] 2023-08-01 02:03
Thanks for the info! That's all I need.

I'm going to close this since you've got your workaround and I've got the info I'm after.

**Closed by sdatkinson** 2023-08-01 02:03 UTC
Labels: bug, priority:low
