### ISSUE TITLE
full stack modelling for guitar only

### ISSUE THREAD

**Issue by jolappi** [sdatkinson/neural-amp-modeler#111] opened 2023-03-04 09:05 UTC
You can now make full  stack model if you dont mind losing almost everything below 90Hz and above 10kHz.
Take this as your training file https://www.dropbox.com/s/5kch9a0w4oqc6ih/v1_1_2.wav?dl=0 
then add to nam/train/core.py this line in to version 
"405a54616574a647005b0befdbed5c50": Version(1, 1, 1),
like this 
    version = {
        "4d54a958861bf720ec4637f43d44a7ef": Version(1, 0, 0),
        "7c3b6119c74465f79d96c761a0e27370": Version(1, 1, 1),
        **"405a54616574a647005b0befdbed5c50": Version(1, 1, 1),**
    }.get(file_hash)
Some one could try to find out what are the actual frequencies we need to cut to be able to still create accurate models of full stack, but mean while happy modeling to you all and remember the cuts are too deep for bass guitar.

**Comment by jolappi** [comment] 2023-03-04 11:44
btw you should use at least 200 epochs for above learning.
Here's little less gutted version of training wav, all under 40Hz and above 13kHz are filtered out https://www.dropbox.com/s/xe0plvsskv03x84/v1_1_3.wav?dl=0
This needs more epochs to get more accurate, at least 300.
And here the checksum for it
"238f8845c6ee1ab01616722b2169c19c": Version(1, 1, 3), add the same way as above to the nam/train/core.py

**Comment by sdatkinson** [comment] 2023-03-04 17:01
Is this for a new capture signal, then?

I've been really happy to let folks "hack" the capture signal, and there's a better way to do it that currently. I think a better way to get you this flexibility without making a new "official" signal (which I want to be conservative on iterating on for others' stability--I want to recommend only one capture signal for simplicity) would be to re-think how the hashing works.

The other thing is that I'd like to see a more complete "battery" of tests to prove that your new capture signal is really improving modeling.

The critical parts of the `v1_1_1.wav` signal are the start and the end. One could hash the audio itself (first 6 seconds and last 9 seconds), which would leave you with the ability to mess with the "bulk" of the signal as you'd like if you want to "hack" it.

**Comment by jolappi** [comment] 2023-03-04 17:41
This is basically copy of v1_1_1.wav with low and high cut filters. 
It might be better if those first 6 seconds and last 9 would be untouched but ill have to test it when i have more time.
But idea in this is that when there's less stuff for AI to learn, it will learn stuff better and we all know that there are certain frequencies that are going to be cut out anyways, hence 40Hz high pass and 13kHz low pass filtering.

**Comment by mikeoliphant** [comment] 2023-03-05 19:00
I been thinking along these lines as well.

One way to check the result would be to compare the output of a normally trained model high/low passed afterward with the the output of a model trained on the high/low passed input signal - also high/low passed afterward.

That should show whether the high/low pass input training actually results in a more accurate reproduction of the desired end frequencies.

**Comment by 2-dor** [comment] 2023-03-05 19:05
I don't know ... a "cured" signal may work for a 6 string guitar in standard tuning but if somebody brings in a baritone guitar (or a 8 or 9 string) to play a model that's been trained that way, not sure how that'll fair. 
The beauty of NAM though is that it's easy to use a custom training signal and hone in on that ideal snapshot but taking data out of the training signal (instead of adding more) would probably only lead to an accurate representation of just some tones

**Comment by mikeoliphant** [comment] 2023-03-05 19:25
The frequencies @jolappi is using are fairly aggressive (particularly on the low end) - ones closer to the limits of human hearing would be more conservative.

It also might make more sense to do the filtering to the output capture file, rather than the input - since amp distortion adds so much harmonic content.

**Comment by jolappi** [comment] 2023-03-06 12:14
Basically, the low pass(not cut) saves so little data that there really is no point to it but on the other hand upper cut when ex. cutting from 15k saves lot more.
Celestion v30 range is 70Hz->5kHz for guitar of course and this is just for metal heads but you can ask yourself how much you miss those hight frequencies ex. above 15k. None after you hit 50 years.
Also I checked Tonex training and it starts to lower(not cut) on 80Hz and after 8kHz thats is why ist learning is easier less frequencies to learn.
I know harmonics are always nice to have but i think the distortion will anyway create those.
I dont know which is easiest for Intellegence to learn, creating something that is missing(input cutted,output not) or
uncreating something that is missing(input no cutted, output cutted).
Anyway it is so dumb or persistent that it wil try to do what ever you ask of it, for as long there is electricity.

I tried without low pass filtering and high pass at 14k and there was no way for me to tell which was original full stack.
14K filtering seems to speed up learning guite lot.

**Comment by sdatkinson** [comment] 2023-03-06 16:13
> This is basically copy of v1_1_1.wav with low and high cut filters. It might be better if those first 6 seconds and last 9 would be untouched but ill have to test it when i have more time. But idea in this is that when there's less stuff for AI to learn, it will learn stuff better and we all know that there are certain frequencies that are going to be cut out anyways, hence 40Hz high pass and 13kHz low pass filtering.

I see.

I'd like to see how well it performs when the cut is not applied to the last 9 seconds. It's important for that last part to be the same so that the comparison is apples to apples.

**Comment by honkkis** [comment] 2023-03-06 21:58
Hey, most of the current models sound very good (better than tonex?) with a drop-tuned baritone and bass even, so please be careful in  encouraging people to capture with frequency limited signals. In the digital domain we are no longer limited to celestion cabs and it is probably enough for most users to do the cutting at the output of the models. 

Probably I am biased since the captures already sound perfect to my ears so they can only get worse :)

**Comment by jolappi** [comment] 2023-03-08 05:54
> > This is basically copy of v1_1_1.wav with low and high cut filters. It might be better if those first 6 seconds and last 9 would be untouched but ill have to test it when i have more time. But idea in this is that when there's less stuff for AI to learn, it will learn stuff better and we all know that there are certain frequencies that are going to be cut out anyways, hence 40Hz high pass and 13kHz low pass filtering.
> 
> I see.
> 
> I'd like to see how well it performs when the cut is not applied to the last 9 seconds. It's important for that last part to be the same so that the comparison is apples to apples.

Here in the zip is original orig.wav and file created with v1_1_6.wav qcorig-nam.wav .
In the v1_1_6.wav beginning and ending are directly from original v1_1_1.wav only middle is low passed at 14k to 20k -48db.
I used lots of distortion as it is harder for AI to learn.
By Ear I cannot hear any difference.
[Archive.zip](https://github.com/sdatkinson/neural-amp-modeler/files/10917605/Archive.zip)

**Comment by jolappi** [comment] 2023-03-12 13:45
Probably training could use more epochs but then time gets over hour or so with mac m2 and without eq adjustment the time triples. Whats time difference using nvidia vs m2, any idea?

**Comment by sdatkinson** [comment] 2024-01-14 20:59
I'm going to close this:
* EQ the _input_ file isn't the same as EQing the _output_ of the amp; the latter is what's usually done when mixing; the former makes the data unrepresentative of how the models are used in practice.
* Full-rig modeling has since been shipped with a different implementation.
* Downstream users are able to modify the training content of the standardized files now without needing to change the hash checks--you should get a weak match which is good enough to make the validation happy.

**Closed by sdatkinson** 2024-01-14 20:59 UTC
Labels: enhancement
