### ISSUE TITLE
(Probably my mistake) anaconda stuck after command conda env create -f environment_gpu.yml

### ISSUE THREAD

**Issue by Corwy991** [sdatkinson/neural-amp-modeler#327] opened 2023-10-30 18:00 UTC
I am going crazy over this and hope someone can help me. 
I have anaconda and GUI installed but after running conda env create -f environment_gpu.yml my shell stucked for hours (it's been 4 hours now and this is the second time I've tried). I have a RTX3080 and want to take advantage of CUDA for training, has this happened to anyone? Thanks.
<img width="755" alt="Stucking " src="https://github.com/sdatkinson/neural-amp-modeler/assets/149421685/3df6bb71-9b96-4997-a743-edc0847b12f6">

**Comment by sdatkinson** [comment] 2023-10-31 15:14
Hi!

Yes, I've noticed this as well while working on #321. I'm not sure exactly how long, but yes, it's quite _long_ all of a sudden. It wasn't like this before and I'd like to see it improved.

**Comment by sdatkinson** [comment] 2023-10-31 15:22
It looks like using the mamba solver makes it quite a bit faster.

Try

```
conda env create -f environment_gpu.yml --experimental-solver=libmamba
```

and let me know how that goes. On my desktop, it took about a minute and a half for everything to run (including downloads and installation; the solving environment itself was about 20 seconds).

If that works for you as well, I'd love a PR updating the README.md with this advice.

Thanks!

**Comment by sdatkinson** [comment] 2023-11-07 01:25
Thanks. I'm going to note the fix in the README and then close this Issue since the original problem is solved with the fix I suggested.

> Everything compiled relatively quickly but I was unable to use the CUDA core as I got the message: No GPU found. Training will be very slow! (I attach the screen)

The first thing I'd suspect is that you used `environment_cpu.yml` instead of `environment_gpu.yml`. What you shared doesn't give me enough information to be sure. If you're still having this problem, we can look at it in a separate issue.

> I saw in another post that there is a way to use RT cores, but the user didn't continue the conversation.

If the Issue is still open then you're welcome to jump in there.

**Closed by sdatkinson** 2023-11-07 01:25 UTC
Labels: enhancement, priority:high
